[package]
name = "linalloc"
version = "2.0.0"
edition = "2024"
rust-version = "1.95"
description = """
Small, lazy commit, fixed-capacity arena allocators for single-threaded Rust programs.
"""
license = "MIT"
repository = "https://github.com/qaijuang/linalloc"
keywords = ["arena", "bump", "allocator", "linear", "memory"]
categories = ["memory-management"]
exclude = [".github", "rustfmt.toml", ".gitignore"]

[package.metadata.docs.rs]
all-features = true

[features]
nightly = []

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "lib"
harness = false
