[package]
name = "linalloc"
version = "1.0.0"
edition = "2024"
rust-version = "1.95"
description = """
Small, fixed-capacity arena allocators for single-threaded Rust programs.
"""
license = "MIT"
repository = "https://github.com/qaijuang/linalloc"
keywords = ["arena", "bump", "allocator", "linear", "memory"]
categories = ["memory-management"]
exclude = [".github", "rustfmt.toml", ".gitignore"]

[features]
default = []
lazy = []

[package.metadata.docs.rs]
all-features = true
